export const REQUEST_LIST_REQUEST = "REQUEST_LIST_REQUEST"
export const REQUEST_LIST_SUCCESS = "REQUEST_LIST_SUCCESS"
export const REQUEST_LIST_FAIL = "REQUEST_LIST_FAIL"

export const REQUEST_DETAILS_REQUEST = "REQUEST_DETAILS_REQUEST"
export const REQUEST_DETAILS_SUCCESS = "REQUEST_DETAILS_SUCCESS"
export const REQUEST_DETAILS_FAIL = "REQUEST_DETAILS_FAIL"

export const NEW_REQUEST_REQUEST = "NEW_REQUEST_REQUEST"
export const NEW_REQUEST_SUCCESS = "NEW_REQUEST_SUCCESS"
export const NEW_REQUEST_FAIL = "NEW_REQUEST_FAIL"

export const UPDATE_REQUEST_REQUEST = "UPDATE_REQUEST_REQUEST"
export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS"
export const UPDATE_REQUEST_FAIL = "UPDATE_REQUEST_FAIL"

export const ALL_REQUESTS_REQUEST = "ALL_REQUESTS_REQUEST"
export const ALL_REQUESTS_SUCCESS = "ALL_REQUESTS_SUCCESS"
export const ALL_REQUESTS_FAIL = "ALL_REQUESTS_FAIL"

export const REQUEST_ByStatus_REQUEST = "REQUEST_DETAILS_REQUEST"
export const REQUEST_ByStatus_SUCCESS = "REQUEST_DETAILS_SUCCESS"
export const REQUEST_ByStatus_FAIL = "REQUEST_DETAILS_FAIL"

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST"
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS"
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL"

