export const REQUEST_LIST_REQUEST = "REQUEST_LIST_REQUEST"
export const REQUEST_LIST_SUCCESS = "REQUEST_LIST_SUCCESS"
export const REQUEST_LIST_FAIL = "REQUEST_LIST_FAIL"

export const REQUEST_DETAILS_REQUEST = "REQUEST_DETAILS_REQUEST"
export const REQUEST_DETAILS_SUCCESS = "REQUEST_DETAILS_SUCCESS"
export const REQUEST_DETAILS_FAIL = "REQUEST_DETAILS_FAIL"